### ISSUE TITLE
Add example of combining features

### ISSUE THREAD

**Issue by leeper** [leeper/cregg#17]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [x] a suggested code or documentation change, improvement to the code, or feature request

It would be nice to demonstrate that if you want higher-order marginal means, you need to combine features together. So if you have two features with levels (A,B), (C,D), you need to create a new factor variable with levels (AC, AD, BC, BD). This is easily done with `interaction()`.

**Comment by mbarnfield** [comment]
I've just seen this after sending a pull request in which I attempted to add some coverage of interactions. Am happy to add this as well/instead. Will it work for AMCEs (i.e., ACIEs) as well?

**Comment by leeper** [comment]
Thanks for that! Yes, those edits look good. This issue is about getting them in the documentation for `cj_amce()` (rather than the vignette). Want to send a separate PR with something like what you have [here](https://github.com/leeper/cregg/pull/21/files/c67c2ff5f91011e570203819630305900538b850..f2d5b1dcdec994e74ce839ae2b1ef21a153c6178#diff-a99280f8e3d02f387e346b79b121a2caR269) added to the docs? Tag the commit message with this issue number.

**Comment by mbarnfield** [comment]
Will do, thanks. I just put everything in the vignette initially as it was my first commit, and if there were issues I thought it would be better if they were all in one place!

**Comment by leeper** [comment]
Totally fine! It's a nice addition to the vignette.

**Comment by mbarnfield** [comment]
Done for amce(), will also do for cj() and mm()
