### ISSUE TITLE
Types of features should be validated.

### ISSUE THREAD

**Issue by zero323** [leeper/cregg#25]
Please specify whether your issue is about:

 - [ ] a possible bug
 - [ ] a question about package functionality
 - [x] a suggested code or documentation change, improvement to the code, or feature request

If you are reporting (1) a bug or (2) a question about code, please supply:

Right now package doesn't validate if `features` are `factors`. It leads to rather errors like this

```R
## load package
library("cregg")

df <- tibble::tibble(
  choice = c(0, 1), f1 = c("a", "b"), f2 = c("d", "e"), id = c("1", "2")
)

mm(df, choice ~ f1 + f2, id = ~id)

## Error in fix.by(by.y, y) : 'by' must specify a uniquely valid column
## In addition: Warning messages:
## 1: Setting row names on a tibble is deprecated. 
## 2: Setting row names on a tibble is deprecated. 
## Called from: fix.by(by.y, y)
```

That's because `make_term_levels_df` [blindly assumes that features are `factors`](https://github.com/leeper/cregg/blob/1c0ec3afea6e58d97ab77292544f3ee493e2b347/R/utils.R#L49) and ends up with a list of `NULLs`

```R
lapply(df[c("f1", "f2")], levels)
## $f1
## NULL
## 
## $f2
## NULL
```

The problem affects at least `amce`, `cj` and `mm`.

A quick fix would be to simply test if that's the case:

```R
if(!all(sapply(data[feature_names], is.factor))) stop("All features should be factors")
```

Alternatively one could attempt to fix the problem by explicitly casting to factors (maybe with a  warning).

**Comment by leeper** [comment]
Thanks. Good points. Will fix.
