### ISSUE TITLE
feature_headers conflicts with facetting

### ISSUE THREAD

**Issue by leeper** [leeper/cregg#8]
The [`feature_headers` code in `plot.cj_...()` methods](https://github.com/leeper/cregg/blob/master/R/plot.R#L83-L86) modifies `x` filling in all other variables in the dataset with `NA`. This messes with facetting by adding an (undesirable) `NA` facet.

**Comment by leeper** [comment]
It is also the reason that there is an `NA` level in the legend when `group` is specified.

**Comment by lairdgallagher** [comment]
Hi Thomas,

I'm encountering this issue where feature_headers = TRUE messes with faceting and adds an NA facet. I see that this undesirable NA facet is still in your example: 
![image](https://user-images.githubusercontent.com/96021641/151242902-79de96d9-a0c6-4f79-94d3-5eab2fb3e8fd.png)

So I figure you have not resolved the bug yet. Is there any way to drop the NA facet and keep feature headers at this time?

Thanks for your help and for this invaluable package!

Laird

**Comment by ralucafpopp** [comment]
Hi,

I'm also curious is there's a way to deal with this undesirable NA facet. Many thanks in advance. :)
